apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name | trunc 63 | trimSuffix "-" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.name | trunc 63 | trimSuffix "-" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name | trunc 63 | trimSuffix "-" }}
    namespace: {{ .Release.Namespace }}
