apiVersion: v1
kind: Service
metadata:
  name: {{ include "project.name" . | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "project.name" . | trunc 63 | trimSuffix "-" | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "project.name" . | trunc 63 | trimSuffix "-" | quote }}
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project.name" . | trunc 63 | trimSuffix "-" | quote }}-echo-ipv4
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "project.name" . | trunc 63 | trimSuffix "-" | quote }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "project.name" . | trunc 63 | trimSuffix "-" | quote }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.echo_server_port }}
      protocol: TCP
    - name: udp
      port: 80
      targetPort: {{ .Values.echo_server_port }}
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project.name" . | trunc 63 | trimSuffix "-" | quote }}-echo-ipv6
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "project.name" . | trunc 63 | trimSuffix "-" | quote }}
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv6
  selector:
    app: {{ include "project.name" . | trunc 63 | trimSuffix "-" | quote }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.echo_server_port }}
      protocol: TCP
    - name: udp
      port: 80
      targetPort: {{ .Values.echo_server_port }}
      protocol: UDP
