apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Values.name | trunc 63 | trimSuffix "-" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name | trunc 63 | trimSuffix "-" }}
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
