name: Call Build Chart

env:
  PR_LABEL: pr/release/robot_update_githubpage
  PR_REVIWER: weizhoublue
  MERGE_BRANCH: github_pages

on:
  workflow_call:
    inputs:
      chart_path:
        required: true
        type: string
      code_sha:
        required: true
        type: string

permissions: write-all

jobs:
  package_chart:
    runs-on: ubuntu-latest
    outputs:
      code_sha: ${{ env.code_sha }}
    steps:
      - name: Get information
        run: |
          echo '${{ toJSON(github) }}'
          # when CI trigger by PR and call this yaml, it appears ${{ github.event_name == 'pull_request' }}
          #if ${{ inputs.ref != '' }}; then
            echo "code_sha=${{ inputs.code_sha }}" >> $GITHUB_ENV
            echo "chart_path=${{ inputs.chart_path }}" >> $GITHUB_ENV
          #else
          #  eixt 1
          #fi

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.code_sha }}

      - name: Install Helm
        uses: azure/setup-helm@v4
        #with:
        #  version: ${{ env.HELM_VERSION }}

      - name: Package Chart
        continue-on-error: false
        run: |
          helm package ${{ env.chart_path }}
          if ! ls *.tgz &>/dev/null ; then
            echo "failed to generate chart"
            exit 1
          fi
          mkdir -p tmp
          mv *.tgz tmp

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: chart_package_artifact
          path: tmp/*
          retention-days: 1
          if-no-files-found: error

  # update /index.yaml in the target branch
  update_githubpage:
    runs-on: ubuntu-latest
    needs: [package_chart]
    steps:
      - name: Get Base Chart URL
        id: get_base_url
        run: |
          name=${{ github.repository }}
          proj=${name#*/}
          url=https://${{ github.repository_owner }}.github.io/${proj}
          echo "URL=${url}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.MERGE_BRANCH }}
          persist-credentials: "true"

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: chart_package_artifact
          path: charts/

      - name: Update Chart Yaml
        run: |
          helm repo index  ./charts  --url ${{ env.URL }}/charts
          mv ./charts/index.yaml ./index.yaml

      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          title: "robot Update chart from ${{ needs.get_ref.outputs.code_sha }} to branch ${{ env.MERGE_BRANCH }} "
          commit-message: "robot Update chart from ${{ needs.get_ref.outputs.code_sha }} to branch ${{ env.MERGE_BRANCH }} "
          branch-suffix: timestamp
          branch: robot/update_chart
          committer: ty-dc <tao.yang@daocloud.io>
          delete-branch: true
          base: ${{ env.MERGE_BRANCH }}
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.PR_LABEL }}
          reviewers: ${{ env.PR_REVIWER }}
