name: Image Latest Rdma Tools

env:
  IMAGE_NAME: rdma-tools
  DOCKERFILE_PATH: rdma-tools/image

on:
  push:
    branches:
      - 'main'
    paths:
      # can not use env here
      - rdma-tools/image/**

permissions: write-all

jobs:
  get_info:
    runs-on: ubuntu-latest
    outputs:
      code_sha: ${{ env.code_sha }}
      image_tag: ${{ env.image_tag }}
      push_image: ${{ env.push_image }}
      image_name: ${{ env.image_name }}
      build_platform: ${{ env.build_platform }}
      upload_artifact: ${{ env.upload_artifact }}
      dockerfile_dirctory: ${{ env.dockerfile_dirctory }}
    steps:
      - name: get information
        run: |
          echo '${{ toJSON(github) }}'
          if ${{ github.event_name == 'push' }} ; then
            echo "call by push tag"
            echo "code_sha=${GITHUB_REF##*/}" >> $GITHUB_ENV
            echo "image_tag=latest" >> $GITHUB_ENV
            echo "push_image=true" >> $GITHUB_ENV
            echo "image_name=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
            echo "dockerfile_dirctory=${{ env.DOCKERFILE_PATH }}" >> $GITHUB_ENV
            echo "build_platform=linux/amd64,linux/arm64" >> $GITHUB_ENV
            echo "upload_artifact=false" >> $GITHUB_ENV
          else
            exit 1
          fi

  call-workflow:
    needs: [get_info]
    uses: ./.github/workflows/callBuildImage.yaml
    with:
      code_sha: ${{ needs.get_info.outputs.code_sha }}
      image_tag: ${{ needs.get_info.outputs.image_tag }}
      push_image: ${{ needs.get_info.outputs.push_image }}
      image_name: ${{ needs.get_info.outputs.image_name }}
      dockerfile_dirctory: ${{ needs.get_info.outputs.dockerfile_dirctory }}
      build_platform: ${{ needs.get_info.outputs.build_platform }}
      upload_artifact: ${{ needs.get_info.outputs.upload_artifact }}
    secrets: inherit
