name: Release Rdma Tools

env:
  CHART_PATH: rdma-tools/chart
  DOCKERFILE_PATH: rdma-tools/image
  IMAGE_NAME: rdma-tools
  BUILD_PLATFORM: linux/amd64
  GEN_DOCKERFILE_SCRIPT: rdma-tools/image/generateDockerfile.sh
  CODE_SHA: ''

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'compile the chart based on the sha or branch of code'
        required: true
        default: main
  push:
    tags:
      - rdma-tools-v[0-9]+.[0-9]+.[0-9]+

permissions: write-all

jobs:
  get_info:
    runs-on: ubuntu-latest
    outputs:
      chart_path: ${{ env.chart_path }}
      code_sha: ${{ env.CODE_SHA }}
      dockerfile_dirctory: ${{ env.DOCKERFILE_PATH }}
      generateDockerfileScript: ${{ env.GEN_DOCKERFILE_SCRIPT }}
      image_name: ${{ env.IMAGE_NAME }}
      build_platform: ${{ env.BUILD_PLATFORM }}
      image_tag: ${{ steps.get_original_ref.outputs.image_tag }}
    steps:
      - name: Get information
        id: get_original_ref
        run: |
          echo '${{ toJSON(github) }}'
          if ${{ github.event_name == 'workflow_dispatch' }}; then
            echo "call by workflow_dispatch"
            echo "CODE_SHA=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
          elif ${{ github.event_name == 'push' }} ; then
            echo "call by push tag"
            echo "CODE_SHA=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          else
            exit 1
          fi
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ steps.get_original_ref.outputs.code_sha }}

      - name: Generate Dockerfile
        run: |
          set -x
          cd ${{ env.DOCKERFILE_PATH }}
          chmod +x ./generateDockerfile.sh
          source ./generateDockerfile.sh
          image_tag=$( git ls-tree --full-tree HEAD -- ${{ env.DOCKERFILE_PATH }} | awk '{ print $3 }' )
          [ -n "${image_tag}" ] || { echo "error, failed to get image_tag from commit id"; exit 1 ; }
          echo "image_tag=${ENV_BASEIMAGE_CUDA_VERISON}-${image_tag}" >> $GITHUB_OUTPUT

  call-image-workflow:
    needs: [get_info]
    uses: ./.github/workflows/callBuildImage.yaml
    with:
      code_sha: ${{ needs.get_info.outputs.code_sha }}
      push_image: true
      image_name: ${{ needs.get_info.outputs.image_name }}
      dockerfile_dirctory: ${{ needs.get_info.outputs.dockerfile_dirctory }}
      build_platform: ${{ needs.get_info.outputs.build_platform }}
      upload_artifact: false
      image_tag: ${{ needs.get_info.outputs.image_tag }}
      generateDockerfileScript: ${{ needs.get_info.outputs.generateDockerfileScript }}
    secrets: inherit

  call-chart-workflow:
    needs: [get_info,call-image-workflow]
    uses: ./.github/workflows/callBuildChart.yaml
    with:
      code_sha: ${{ needs.get_info.outputs.code_sha }}
      chart_path: ${{ needs.get_info.outputs.chart_path }}
    secrets: inherit
